FROM debian
ADD debian.list /etc/apt/sources.list.d/
RUN apt-get update && apt-get -y upgrade && apt -y install nginx && apt-get clean && \
    cd /var/www/ && rm -rf ./* && \
    mkdir -p davaipozhenimsya.com/img && \
    chmod -R 754 /var/www/davaipozhenimsya.com/ && \
    useradd Elizaveta && groupadd Monchakovskaya && usermod -aG Monchakovskaya Elizaveta && \
    chown -R Elizaveta:Monchakovskaya /var/www/davaipozhenimsya.com/ && \
    sed -i 's/\/var\/www\/html/\/var\/www\/davaipozhenimsya.com/g' /etc/nginx/sites-enabled/default && \
    sed -i 's/user www-data/user Elizaveta/g' /etc/nginx/nginx.conf
ADD index.html /var/www/davaipozhenimsya.com/
ADD img.jpg /var/www/davaipozhenimsya.com/img/
CMD ["nginx", "-g", "daemon off;"]
